### ISSUE TITLE
Please be more specific

### ISSUE THREAD

**Issue by Atulkmr** [jg-fisher/desktopAssistant#1]
1. Provide the requirements file, dependencies. For eg. [this page ](https://pypi.python.org/pypi/SpeechRecognition/ )  says that I need to have PyAudio in order for the microphone to work, this was never mentioned.
2. Instructions on how to run the program.
3. Comments about functions should rather be mentioned as docstrings for accessibility reasons.

**Comment by jg-fisher** [comment]
I will update the project with these things. Thank you!

**Comment by dseptem** [comment]
You closed the issue but you didn't solve it.
