### ISSUE TITLE
Spanish support

### ISSUE THREAD

**Issue by dseptem** [jg-fisher/desktopAssistant#5]
I suppose that this doesn't work in spanish "out-of-the-box", right?
How would one adjust the script for it to function with another language?

**Comment by neyerdav** [comment]
You should translate the commads with https://docs.python.org/3/library/gettext.html.
gtts supports spanish.

**Comment by dseptem** [comment]
If gtts supports spanish, why translate the received command?

Edit: So it works with the current implementation I guess? I would create my own commands in spanish.

**Comment by neyerdav** [comment]
You need to change the en here text_to_speech = gTTS(text=audio, lang='en') to es and the commands like "open reddit" and "what\'s up" into spanish

**Comment by dseptem** [comment]
Thanks, it worked!

**Comment by dseptem** [comment]
Documentation could be added for people who want to use another language, though.

**Comment by neyerdav** [comment]
Thats Not the correct way. You should have used Gettext

**Comment by dseptem** [comment]
Sorry, but I fail to see how translating from spanish to english is going to help, since I'm a native spanish speaker and I can code my own commands in spanish. BTW, I'm using slang from my country which cannot be easily translated, but Google recognizes it.
What is Gettext's purpose here?
